/**
 * Corruption Perceptions Index (CPI) 2024 — Transparency International.
 * Score ranges 0 (highly corrupt) to 100 (very clean). Released Feb 2025.
 * Authoritative source: https://www.transparency.org/en/cpi/2024
 *
 * Values below reflect the published CPI 2024 dataset to the best knowledge
 * available; verify against transparency.org before quoting.
 */

const CPI_YEAR = 2024;

// alpha-3 ISO code -> { name, score }
const CPI_DATA = {
  DNK: { name: "Denmark", score: 90 },
  FIN: { name: "Finland", score: 88 },
  SGP: { name: "Singapore", score: 84 },
  NZL: { name: "New Zealand", score: 83 },
  LUX: { name: "Luxembourg", score: 81 },
  NOR: { name: "Norway", score: 81 },
  CHE: { name: "Switzerland", score: 81 },
  SWE: { name: "Sweden", score: 80 },
  NLD: { name: "Netherlands", score: 78 },
  AUS: { name: "Australia", score: 77 },
  ISL: { name: "Iceland", score: 77 },
  IRL: { name: "Ireland", score: 77 },
  EST: { name: "Estonia", score: 76 },
  URY: { name: "Uruguay", score: 76 },
  CAN: { name: "Canada", score: 75 },
  DEU: { name: "Germany", score: 75 },
  HKG: { name: "Hong Kong", score: 74 },
  BTN: { name: "Bhutan", score: 72 },
  SYC: { name: "Seychelles", score: 72 },
  JPN: { name: "Japan", score: 71 },
  GBR: { name: "United Kingdom", score: 71 },
  BEL: { name: "Belgium", score: 69 },
  ARE: { name: "United Arab Emirates", score: 68 },
  BRB: { name: "Barbados", score: 68 },
  AUT: { name: "Austria", score: 67 },
  FRA: { name: "France", score: 67 },
  TWN: { name: "Taiwan", score: 67 },
  USA: { name: "United States", score: 65 },
  ISR: { name: "Israel", score: 64 },
  KOR: { name: "South Korea", score: 64 },
  BHS: { name: "Bahamas", score: 63 },
  CHL: { name: "Chile", score: 63 },
  LTU: { name: "Lithuania", score: 63 },
  CPV: { name: "Cabo Verde", score: 62 },
  DMA: { name: "Dominica", score: 60 },
  LVA: { name: "Latvia", score: 60 },
  SVN: { name: "Slovenia", score: 60 },
  BRN: { name: "Brunei", score: 60 },
  QAT: { name: "Qatar", score: 59 },
  SAU: { name: "Saudi Arabia", score: 59 },
  CRI: { name: "Costa Rica", score: 58 },
  PRT: { name: "Portugal", score: 57 },
  RWA: { name: "Rwanda", score: 57 },
  BWA: { name: "Botswana", score: 57 },
  ESP: { name: "Spain", score: 56 },
  CZE: { name: "Czechia", score: 56 },
  OMN: { name: "Oman", score: 55 },
  ITA: { name: "Italy", score: 54 },
  POL: { name: "Poland", score: 53 },
  GEO: { name: "Georgia", score: 53 },
  BHR: { name: "Bahrain", score: 53 },
  FJI: { name: "Fiji", score: 52 },
  GRD: { name: "Grenada", score: 53 },
  MYS: { name: "Malaysia", score: 50 },
  GRC: { name: "Greece", score: 49 },
  NAM: { name: "Namibia", score: 49 },
  SVK: { name: "Slovakia", score: 49 },
  VUT: { name: "Vanuatu", score: 48 },
  HRV: { name: "Croatia", score: 47 },
  ARM: { name: "Armenia", score: 47 },
  JOR: { name: "Jordan", score: 46 },
  ROU: { name: "Romania", score: 46 },
  MLT: { name: "Malta", score: 46 },
  KWT: { name: "Kuwait", score: 46 },
  MNE: { name: "Montenegro", score: 46 },
  CIV: { name: "Côte d'Ivoire", score: 45 },
  SEN: { name: "Senegal", score: 45 },
  TTO: { name: "Trinidad and Tobago", score: 42 },
  TLS: { name: "Timor-Leste", score: 44 },
  JAM: { name: "Jamaica", score: 44 },
  BGR: { name: "Bulgaria", score: 43 },
  CHN: { name: "China", score: 43 },
  BEN: { name: "Benin", score: 43 },
  MDA: { name: "Moldova", score: 43 },
  GHA: { name: "Ghana", score: 42 },
  SLB: { name: "Solomon Islands", score: 42 },
  WSM: { name: "Samoa", score: 42 },
  ALB: { name: "Albania", score: 42 },
  HUN: { name: "Hungary", score: 41 },
  CUB: { name: "Cuba", score: 41 },
  ZAF: { name: "South Africa", score: 41 },
  PRY: { name: "Paraguay", score: 41 },
  BFA: { name: "Burkina Faso", score: 41 },
  KAZ: { name: "Kazakhstan", score: 40 },
  TZA: { name: "Tanzania", score: 40 },
  VNM: { name: "Vietnam", score: 40 },
  COL: { name: "Colombia", score: 39 },
  GUY: { name: "Guyana", score: 39 },
  MKD: { name: "North Macedonia", score: 39 },
  TUN: { name: "Tunisia", score: 39 },
  ZMB: { name: "Zambia", score: 39 },
  IND: { name: "India", score: 38 },
  ETH: { name: "Ethiopia", score: 37 },
  IDN: { name: "Indonesia", score: 37 },
  ARG: { name: "Argentina", score: 37 },
  LSO: { name: "Lesotho", score: 37 },
  MAR: { name: "Morocco", score: 37 },
  GMB: { name: "Gambia", score: 36 },
  SUR: { name: "Suriname", score: 36 },
  DOM: { name: "Dominican Republic", score: 35 },
  SRB: { name: "Serbia", score: 35 },
  UKR: { name: "Ukraine", score: 35 },
  THA: { name: "Thailand", score: 34 },
  TUR: { name: "Türkiye", score: 34 },
  BRA: { name: "Brazil", score: 34 },
  DZA: { name: "Algeria", score: 34 },
  DJI: { name: "Djibouti", score: 34 },
  MWI: { name: "Malawi", score: 34 },
  NPL: { name: "Nepal", score: 34 },
  PHL: { name: "Philippines", score: 33 },
  BIH: { name: "Bosnia and Herzegovina", score: 33 },
  BLR: { name: "Belarus", score: 33 },
  MNG: { name: "Mongolia", score: 33 },
  PAN: { name: "Panama", score: 33 },
  SLE: { name: "Sierra Leone", score: 33 },
  KEN: { name: "Kenya", score: 32 },
  AGO: { name: "Angola", score: 32 },
  ECU: { name: "Ecuador", score: 32 },
  LKA: { name: "Sri Lanka", score: 32 },
  UZB: { name: "Uzbekistan", score: 32 },
  PER: { name: "Peru", score: 31 },
  PNG: { name: "Papua New Guinea", score: 31 },
  EGY: { name: "Egypt", score: 30 },
  PSE: { name: "Palestine", score: 30 },
  SLV: { name: "El Salvador", score: 30 },
  TGO: { name: "Togo", score: 30 },
  MRT: { name: "Mauritania", score: 30 },
  GIN: { name: "Guinea", score: 28 },
  LAO: { name: "Laos", score: 28 },
  MLI: { name: "Mali", score: 28 },
  BOL: { name: "Bolivia", score: 28 },
  GAB: { name: "Gabon", score: 28 },
  PAK: { name: "Pakistan", score: 27 },
  CMR: { name: "Cameroon", score: 27 },
  SWZ: { name: "Eswatini", score: 27 },
  MEX: { name: "Mexico", score: 26 },
  NGA: { name: "Nigeria", score: 26 },
  UGA: { name: "Uganda", score: 26 },
  IRQ: { name: "Iraq", score: 26 },
  CAF: { name: "Central African Republic", score: 26 },
  MDG: { name: "Madagascar", score: 26 },
  NER: { name: "Niger", score: 26 },
  LBR: { name: "Liberia", score: 25 },
  GTM: { name: "Guatemala", score: 25 },
  KGZ: { name: "Kyrgyzstan", score: 25 },
  MOZ: { name: "Mozambique", score: 25 },
  GNB: { name: "Guinea-Bissau", score: 23 },
  BGD: { name: "Bangladesh", score: 23 },
  IRN: { name: "Iran", score: 23 },
  RUS: { name: "Russia", score: 22 },
  HND: { name: "Honduras", score: 22 },
  LBN: { name: "Lebanon", score: 22 },
  AZE: { name: "Azerbaijan", score: 22 },
  ZWE: { name: "Zimbabwe", score: 21 },
  KHM: { name: "Cambodia", score: 21 },
  TCD: { name: "Chad", score: 21 },
  COG: { name: "Republic of the Congo", score: 21 },
  COD: { name: "DR Congo", score: 20 },
  BDI: { name: "Burundi", score: 20 },
  TJK: { name: "Tajikistan", score: 19 },
  COM: { name: "Comoros", score: 19 },
  AFG: { name: "Afghanistan", score: 17 },
  TKM: { name: "Turkmenistan", score: 17 },
  HTI: { name: "Haiti", score: 16 },
  MMR: { name: "Myanmar", score: 16 },
  SDN: { name: "Sudan", score: 15 },
  NIC: { name: "Nicaragua", score: 14 },
  ERI: { name: "Eritrea", score: 13 },
  GNQ: { name: "Equatorial Guinea", score: 13 },
  LBY: { name: "Libya", score: 13 },
  YEM: { name: "Yemen", score: 13 },
  SYR: { name: "Syria", score: 12 },
  VEN: { name: "Venezuela", score: 10 },
  SOM: { name: "Somalia", score: 9 },
  SSD: { name: "South Sudan", score: 8 },
  PRK: { name: "North Korea", score: 17 }
};

// ISO 3166-1 numeric (string, zero-padded) -> alpha-3
// Used to join with world-atlas TopoJSON (feature.id is numeric).
const NUMERIC_TO_ALPHA3 = {
  "004": "AFG", "008": "ALB", "012": "DZA", "024": "AGO", "032": "ARG",
  "036": "AUS", "040": "AUT", "031": "AZE", "044": "BHS", "048": "BHR",
  "050": "BGD", "051": "ARM", "052": "BRB", "056": "BEL", "064": "BTN",
  "068": "BOL", "070": "BIH", "072": "BWA", "076": "BRA", "084": "BLZ",
  "090": "SLB", "096": "BRN", "100": "BGR", "104": "MMR", "108": "BDI",
  "112": "BLR", "116": "KHM", "120": "CMR", "124": "CAN", "132": "CPV",
  "140": "CAF", "144": "LKA", "148": "TCD", "152": "CHL", "156": "CHN",
  "158": "TWN", "170": "COL", "174": "COM", "178": "COG", "180": "COD",
  "188": "CRI", "191": "HRV", "192": "CUB", "196": "CYP", "203": "CZE",
  "204": "BEN", "208": "DNK", "214": "DOM", "218": "ECU", "222": "SLV",
  "226": "GNQ", "231": "ETH", "232": "ERI", "233": "EST", "242": "FJI",
  "246": "FIN", "250": "FRA", "262": "DJI", "266": "GAB", "268": "GEO",
  "270": "GMB", "275": "PSE", "276": "DEU", "288": "GHA", "300": "GRC",
  "320": "GTM", "324": "GIN", "328": "GUY", "332": "HTI", "340": "HND",
  "344": "HKG", "348": "HUN", "352": "ISL", "356": "IND", "360": "IDN",
  "364": "IRN", "368": "IRQ", "372": "IRL", "376": "ISR", "380": "ITA",
  "384": "CIV", "388": "JAM", "392": "JPN", "398": "KAZ", "400": "JOR",
  "404": "KEN", "408": "PRK", "410": "KOR", "414": "KWT", "417": "KGZ",
  "418": "LAO", "422": "LBN", "426": "LSO", "428": "LVA", "430": "LBR",
  "434": "LBY", "440": "LTU", "442": "LUX", "450": "MDG", "454": "MWI",
  "458": "MYS", "466": "MLI", "478": "MRT", "480": "MUS", "484": "MEX",
  "496": "MNG", "498": "MDA", "499": "MNE", "504": "MAR", "508": "MOZ",
  "512": "OMN", "516": "NAM", "524": "NPL", "528": "NLD", "548": "VUT",
  "554": "NZL", "558": "NIC", "562": "NER", "566": "NGA", "578": "NOR",
  "586": "PAK", "591": "PAN", "598": "PNG", "600": "PRY", "604": "PER",
  "608": "PHL", "616": "POL", "620": "PRT", "624": "GNB", "626": "TLS",
  "630": "PRI", "634": "QAT", "642": "ROU", "643": "RUS", "646": "RWA",
  "682": "SAU", "686": "SEN", "688": "SRB", "690": "SYC", "694": "SLE",
  "702": "SGP", "703": "SVK", "704": "VNM", "705": "SVN", "706": "SOM",
  "710": "ZAF", "716": "ZWE", "724": "ESP", "728": "SSD", "729": "SDN",
  "740": "SUR", "748": "SWZ", "752": "SWE", "756": "CHE", "760": "SYR",
  "762": "TJK", "764": "THA", "768": "TGO", "780": "TTO", "784": "ARE",
  "788": "TUN", "792": "TUR", "795": "TKM", "800": "UGA", "804": "UKR",
  "807": "MKD", "818": "EGY", "826": "GBR", "834": "TZA", "840": "USA",
  "854": "BFA", "858": "URY", "860": "UZB", "862": "VEN", "882": "WSM",
  "887": "YEM", "894": "ZMB"
};
