/*
 * Financial Intelligence Monitor — indicative macro dataset
 * Keys MUST match country names in world-atlas@2 countries-110m.json
 * Scores 0–100:
 *   scam         : prevalence of scam / fraud activity (higher = worse)
 *   embezzlement : embezzlement / public-fund corruption (higher = worse)
 *   enforcement  : law-enforcement effectiveness (higher = better)
 * Replace these indicative values with your own sourced figures.
 */
const DATA = {
  "United States of America":{scam:62,embezzlement:38,enforcement:78},
  "Canada":{scam:41,embezzlement:25,enforcement:82},
  "Mexico":{scam:68,embezzlement:71,enforcement:42},
  "Brazil":{scam:64,embezzlement:69,enforcement:46},
  "Argentina":{scam:58,embezzlement:66,enforcement:48},
  "Chile":{scam:44,embezzlement:38,enforcement:67},
  "Colombia":{scam:66,embezzlement:64,enforcement:45},
  "Peru":{scam:60,embezzlement:67,enforcement:43},
  "Venezuela":{scam:74,embezzlement:88,enforcement:22},
  "United Kingdom":{scam:55,embezzlement:30,enforcement:79},
  "Ireland":{scam:43,embezzlement:28,enforcement:76},
  "France":{scam:52,embezzlement:34,enforcement:74},
  "Germany":{scam:48,embezzlement:27,enforcement:80},
  "Spain":{scam:54,embezzlement:42,enforcement:70},
  "Portugal":{scam:50,embezzlement:40,enforcement:69},
  "Italy":{scam:58,embezzlement:55,enforcement:62},
  "Netherlands":{scam:45,embezzlement:24,enforcement:81},
  "Belgium":{scam:47,embezzlement:31,enforcement:75},
  "Switzerland":{scam:38,embezzlement:22,enforcement:84},
  "Austria":{scam:42,embezzlement:29,enforcement:78},
  "Norway":{scam:33,embezzlement:18,enforcement:88},
  "Sweden":{scam:36,embezzlement:20,enforcement:86},
  "Finland":{scam:31,embezzlement:16,enforcement:89},
  "Denmark":{scam:30,embezzlement:15,enforcement:90},
  "Poland":{scam:53,embezzlement:44,enforcement:66},
  "Ukraine":{scam:70,embezzlement:78,enforcement:38},
  "Russia":{scam:72,embezzlement:84,enforcement:35},
  "Belarus":{scam:65,embezzlement:80,enforcement:40},
  "Romania":{scam:60,embezzlement:58,enforcement:55},
  "Greece":{scam:57,embezzlement:52,enforcement:60},
  "Turkey":{scam:66,embezzlement:62,enforcement:50},
  "China":{scam:69,embezzlement:60,enforcement:58},
  "India":{scam:71,embezzlement:65,enforcement:49},
  "Pakistan":{scam:73,embezzlement:74,enforcement:39},
  "Bangladesh":{scam:70,embezzlement:72,enforcement:41},
  "Japan":{scam:40,embezzlement:23,enforcement:83},
  "South Korea":{scam:46,embezzlement:35,enforcement:74},
  "Indonesia":{scam:67,embezzlement:63,enforcement:47},
  "Philippines":{scam:75,embezzlement:68,enforcement:44},
  "Vietnam":{scam:62,embezzlement:61,enforcement:52},
  "Thailand":{scam:64,embezzlement:59,enforcement:53},
  "Malaysia":{scam:58,embezzlement:54,enforcement:60},
  "Singapore":{scam:39,embezzlement:19,enforcement:87},
  "Australia":{scam:44,embezzlement:24,enforcement:83},
  "New Zealand":{scam:35,embezzlement:17,enforcement:88},
  "Saudi Arabia":{scam:55,embezzlement:57,enforcement:61},
  "Iran":{scam:71,embezzlement:79,enforcement:37},
  "Iraq":{scam:74,embezzlement:83,enforcement:30},
  "Israel":{scam:48,embezzlement:33,enforcement:75},
  "Egypt":{scam:68,embezzlement:70,enforcement:45},
  "South Africa":{scam:69,embezzlement:67,enforcement:48},
  "Nigeria":{scam:82,embezzlement:81,enforcement:33},
  "Kenya":{scam:72,embezzlement:71,enforcement:43},
  "Ghana":{scam:66,embezzlement:60,enforcement:50},
  "Ethiopia":{scam:64,embezzlement:68,enforcement:42},
  "Morocco":{scam:60,embezzlement:58,enforcement:54},
  "Algeria":{scam:63,embezzlement:69,enforcement:46},
  "Dem. Rep. Congo":{scam:76,embezzlement:86,enforcement:25},
  "Angola":{scam:70,embezzlement:82,enforcement:34},
  "Kazakhstan":{scam:61,embezzlement:73,enforcement:47},
  "United Arab Emirates":{scam:50,embezzlement:40,enforcement:72}
};
